--tasks
--

ALTER TABLE alarm
RENAME COLUMN readydat TO createdat

-- TIME  DATE
ALTER TABLE alarm
ADD COLUMN readydat TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


ALTER TABLE tasks
ADD COLUMN priority INT DEFAULT 4;


CREATE TABLE tasks (
    id SERIAL PRIMARY KEY,
    text TEXT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
